# https://golangci-lint.run/usage/configuration
version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused
    - misspell
    - nakedret
    - bodyclose
    - gocritic
    - makezero
    - gosec
    - unconvert
    - noctx
    - prealloc
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    staticcheck:
      checks:
        - all
        - "-QF1008" # Allow embedded structs to be referenced by field
        - "-ST1000" # Do not require package comments
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    gosec:
      # Exclude G301 (directory permissions) - workspace needs readable directories
      # Exclude G304 (file inclusion) - paths are validated via safePath()
      # Exclude G306 (file permissions) - workspace files need to be readable
      excludes:
        - G301
        - G304
        - G306

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
